import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const tempFile = path.join(__dirname, '../../temp_map_data.txt');
const outputFile = path.join(__dirname, '../../src/tools/contact-management/utils/malaysiaSVGMap.js');

console.log(`Reading from ${tempFile}`);
const content = fs.readFileSync(tempFile, 'utf8');

// Extract MALAYSIA_SVG_PATHS
const pathsStart = content.indexOf('export const MALAYSIA_SVG_PATHS = {');
if (pathsStart === -1) {
    console.error('Could not find MALAYSIA_SVG_PATHS start');
    process.exit(1);
}
const pathsEnd = content.indexOf('};', pathsStart) + 2;
const pathsBlock = content.substring(pathsStart, pathsEnd);

// Extract STATE_LABEL_POSITIONS
const labelsStart = content.indexOf('export const STATE_LABEL_POSITIONS = {');
if (labelsStart === -1) {
    console.error('Could not find STATE_LABEL_POSITIONS start');
    process.exit(1);
}
const labelsEnd = content.indexOf('};', labelsStart) + 2;
const labelsBlock = content.substring(labelsStart, labelsEnd);

const finalContent = `
// Malaysia Map Data
// Generated by scripts/map-gen/generate_paths.js

export const MAP_CONFIG = {
  width: 600,
  height: 500,
  viewBox: '0 0 600 500'
};

${pathsBlock}

${labelsBlock}

// Helper function to get label position
export function getLabelPosition(stateName) {
  return STATE_LABEL_POSITIONS[stateName] || { x: 0, y: 0 };
}
`;

console.log(`Writing to ${outputFile}`);
fs.writeFileSync(outputFile, finalContent);
console.log('Successfully wrote malaysiaSVGMap.js');
