// Code Generated By 'npm run config', Please DO NOT Edit!!!!! 
        
const config = {
    appId: "cli_a7c6350f9778d010", //网页应用appId
    appSecret: "cMfrfWMK5vppT6zh89zzohz5jby8GiRc", //网页应用secret
    getUserAccessTokenPath:  "/api/get_user_access_token", //免登-获取user_access_token的api path
    getSignParametersPath:  "/api/get_sign_parameters", //鉴权-获取鉴权参数的api path
    getOrganizationMembersPath: "/api/get_organization_members", //获取组织成员列表的api path
    getDepartmentsPath: "/api/get_departments", //获取部门列表的api path
    getDepartmentUsersPath: "/api/get_department_users", //获取部门用户列表的api path
    getBitableTablesPath: "/api/get_bitable_tables", //获取多维表格表列表的api path
    noncestr: "TRnJnK2X7MtMiMDHwwdR38hnebbdeMAE",   //随机字符串，用于鉴权签名用
    apiPort: "8989",   //后端指定端口
}
    
module.exports = { config : config };