// Code Generated By 'npm run config', Please DO NOT Edit!!!!! 
        
const clientConfig = {
    appId: "cli_a7c6350f9778d010", //网页应用appId
    getUserAccessTokenPath:  "/api/get_user_access_token", //免登api path
    getSignParametersPath:  "/api/get_sign_parameters", //鉴权api path;
    getOrganizationMembersPath: "/api/get_organization_members", //获取组织成员列表api path
    getDepartmentsPath: "/api/get_departments", //获取部门列表api path
    getDepartmentUsersPath: "/api/get_department_users", //获取部门用户列表api path
    apiPort: "8989",   //后端指定端口
    apiOrigin: "",   // 后端完整公开地址(优先使用)，例如 https://abc123.ngrok.io
}
    
export default clientConfig;